FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04


RUN apt-get -y update && apt-get -y upgrade && \
  apt-get install -y python3 python3-pip python3-dev
RUN pip install vllm

COPY docker/vllm_entrypoint.sh /vllm_entrypoint.sh

ENTRYPOINT [ "bash", "/vllm_entrypoint.sh"]
