FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get -y update && apt-get -y upgrade && \
  apt-get install -y \
  python3 python3-pip python3-dev \
  python3-pyaudio portaudio19-dev

RUN pip install whisper flask

COPY src/asr/api.py /api.py
COPY docker/asr_entrypoint.sh /asr_entrypoint.sh

ENTRYPOINT [ "bash", "/asr_entrypoint.sh" ]
