FROM ubuntu:20.04

RUN apt-get -y update && apt-get -y upgrade && \
  apt-get install -y \
  python3 python3-pip python3-dev \
  python3-pyaudio alsa-base alsa-utils

COPY src/chatbot /chatbot
COPY docker/requirements-chatbot.txt /requirements-chatbot.txt

RUN pip install -r /requirements-chatbot.txt

COPY docker/chatbot_entrypoint.sh /chatbot_entrypoint.sh
ENTRYPOINT [ "bash", "/chatbot_entrypoint.sh" ]
