version: "3"

services:
  vllm:
    runtime: nvidia
    build:
      context : ..
      dockerfile: Dockerfile.vllm
    environment:
      - MODEL=TheBloke/Vigostral-7B-Chat-AWQ
      - QUANTIZATION=awq
      - MAX_MODEL_LEN=1024
      - GPU_MEMORY_UTILIZATION=0.4
    networks:
      network:
        ipv4_address: 10.5.0.2

  tts:
    runtime: nvidia
    build:
      context: ..
      dockerfile: docker/Dockerfile.tts
    environment:
      - MODEL=tts_models/fr/mai/tacotron2-DDC
      - DEVICE=cpu
    networks:
      network:
        ipv4_address: 10.5.0.3

  asr:
    runtime: nvidia
    build:
      context: ..
      dockerfile: docker/Dockerfile.asr
    environment:
      - MODEL=bofenghuang/whisper-small-cv11-french
      - DEVICE=cuda
    networks:
      network:
        ipv4_address: 10.5.0.4

  chatbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.chatbot
    environment:
      - ASR_API_HOST=asr
      - ASR_API_PORT=5000
      - TTS_API_HOST=tts
      - TTS_API_PORT=5000
      - LLM_API_HOST=vllm
      - LLM_API_PORT=8000
    networks:
      network:
        ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
