FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get -y update && apt-get -y upgrade && \
  apt-get install -y python3 python3-pip python3-dev

RUN pip install \
  TTS \
  flask

COPY src/tts/tts_api.py /tts_api.py
COPY docker/tts_entrypoint.sh /tts_entrypoint.sh

ENTRYPOINT [ "bash", "/tts_entrypoint.sh" ]